### ISSUE TITLE
got error from forwardee: EOF

### ISSUE THREAD

**Issue by mcineran** [mkevac/goduplicator#5]
Hi, i'm using this with rrdcached (as i couldn't find anything else suitable)
https://oss.oetiker.ch/rrdtool/doc/rrdcached.en.html

/goduplicator -l 0.0.0.0:42218 -f x.x.x.x:42217 -m x.x.x.x:42217

-f is the local address of the same machine where the service is running.
-m is the remote address for the other memcached i want populated with the same data.

It then logs repeatedly:
(accepted connection)
got error from forwardee: EOF

However the rrd's appear to be populated correctly, so it seems to be working fine.

For now I've turned off logging anything.

Any ideas?

**Comment by mkevac** [comment]
You are right. EOF is not an error. I think I've fixed the problem in the latest version. Can you try it? Thanks!

**Comment by mcineran** [comment]
Yes, fully tested and working. No further errors. Thanks very much.
