### ISSUE TITLE
open files with rrdcached

### ISSUE THREAD

**Issue by mcineran** [mkevac/goduplicator#6]
Hi, sorry to bother you so soon with another issue.

I had to look into some performance issues and discovered I was running into ulimit / sysctl limits. I increased the limits and had a look.

 lsof | awk '{print $1}' | sort | uniq -c | sort -r -n | head
 834823 rrdcached
  24252 goduplica

I thought rrdcached was causing the problem and upgraded it to the latest version, which sorted out a few crashes with rrdcached.

However taking goduplicator out of the equation and having both pollers report to the one rrdcached instance the problem disappeared. (So, the exact same traffic flow)

I haven't much luck parsing my way through the code at the moment, but I'm assuming it needs to close a file or tcp socket somewhere....

**Comment by mkevac** [comment]
I think I've fixed it in 0.2.2, but, to be honest, you are the first user of this hackish tool and there are a lot of other corner cases out there. I should spend some more time polishing it.

**Comment by mkevac** [comment]
Feel free to open another bug if there is still a problem or if there are new problems. I'll try and fix it up for you.

**Comment by mcineran** [comment]
Tested and working, it's not showing up in lsof now at all, and it's stopped affecting rrdcached too.

Fantastic, thanks very much!

**Comment by mcineran** [comment]
Actually just briefly I was wondering what the zero copy option was for?

**Comment by mkevac** [comment]
Mirroring traffic is reading the data from the network and then sending the data. In a simple case you copy data from kernel to user space and then from user space to kernel. There is a certain overhead.
Zero copy uses splice system call to read and send that data only in kernel, without the need to copy it to user space.
It should be useful for high throughput situations.
But, again, this tool was my weekend project and it has not been thoroughly tested as you already know :-)
